# Copyright © 2017 Martin Ueding <dev@martin-ueding.de>

language: cpp
script: ./travis-ci.sh
dist: trusty
sudo: true

python:
    - "3.5"

notifications:
    slack: qphix:CL3hceIh0CHiXctnpvR6hXZs

cache: ccache

env:
    - QPHIX_ARCH=SCALAR
    - QPHIX_ARCH=AVX
    - QPHIX_ARCH=AVX2
    - QPHIX_ARCH=AVX512
