# Copyright © 2017 Martin Ueding <dev@martin-ueding.de>

language: cpp
script: ./travis-ci.sh
dist: trusty
sudo: true

notifications:
    slack: qphix:CL3hceIh0CHiXctnpvR6hXZs

cache: ccache

env:
    - QPHIX_ARCH=scalar
    - QPHIX_ARCH=AVX
    - QPHIX_ARCH=AVX2
