// This file has been automatically generated by mu on martin-friese on 2017-02-10 19:55 +0000. Do not change it manually, rather look for the template in qphix-codegen.

#pragma once



#if defined (QPHIX_AVX_SOURCE)
#warning "including qphix/avx/ndtm_clov_dslash_avx_complete_specialization.h"
#include "qphix/avx/ndtm_clov_dslash_avx_complete_specialization.h"
#endif


#if defined (QPHIX_AVX2_SOURCE)
#warning "including qphix/avx2/ndtm_clov_dslash_avx2_complete_specialization.h"
#include "qphix/avx2/ndtm_clov_dslash_avx2_complete_specialization.h"
#endif


#if defined (QPHIX_AVX512_SOURCE)
#warning "including qphix/avx512/ndtm_clov_dslash_avx512_complete_specialization.h"
#include "qphix/avx512/ndtm_clov_dslash_avx512_complete_specialization.h"
#endif


#if defined (QPHIX_MIC_SOURCE)
#warning "including qphix/mic/ndtm_clov_dslash_mic_complete_specialization.h"
#include "qphix/mic/ndtm_clov_dslash_mic_complete_specialization.h"
#endif


#if defined (QPHIX_QPX_SOURCE)
#warning "including qphix/qpx/ndtm_clov_dslash_qpx_complete_specialization.h"
#include "qphix/qpx/ndtm_clov_dslash_qpx_complete_specialization.h"
#endif


#if defined (QPHIX_SCALAR_SOURCE)
#warning "including qphix/scalar/ndtm_clov_dslash_scalar_complete_specialization.h"
#include "qphix/scalar/ndtm_clov_dslash_scalar_complete_specialization.h"
#endif


#if defined (QPHIX_SSE_SOURCE)
#warning "including qphix/sse/ndtm_clov_dslash_sse_complete_specialization.h"
#include "qphix/sse/ndtm_clov_dslash_sse_complete_specialization.h"
#endif
